#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenType {
    // Basic identifiers and literals
    IDENT,
    NUMBER,
    STRING,
    TRUE,
    FALSE,
    
    // Keywords
    FUNCTION,
    IF,
    ELSE,
    ELIF,
    WHILE,
    FOR,
    IN,
    LET,
    IS,
    AS,
    TYPE,
    INHERITS,
    NEW,
    SELF,
    BASE,
    
    // Brackets and delimiters
    LPAREN,
    RPAREN,
    LBRACE,
    RBRACE,
    SEMICOLON,
    COMMA,
    COLON,
    DOT,
    
    // Operators
    PLUS,
    MINUS,
    MULT,
    DIV,
    MOD,
    POW,
    ASSIGN,
    ASSIGN_DESTRUCT,
    ARROW,
    LT,
    GT,
    LE,
    GE,
    EQ,
    NEQ,
    OR,
    AND,
    CONCAT,
    CONCAT_WS,
    
    // End of file
    EOF,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub token_type: TokenType,
    pub lexeme: String,
    pub line: usize,
    pub column: usize,
}

// Helper function to create a token
pub fn make_token(token_type: TokenType, lexeme: &str, line: usize, column: usize) -> Token {
    Token {
        token_type,
        lexeme: lexeme.to_string(),
        line,
        column,
    }
}

/// Returns a list of mock tokens for testing
pub fn mock_tokens() -> Vec<Token> {
    // vec![
    //     make_token(TokenType::NUMBER, "2", 1, 1),
    //     make_token(TokenType::PLUS, "+", 1, 2),
    //     make_token(TokenType::NUMBER, "3", 1, 3),
    //     make_token(TokenType::SEMICOLON, ";", 1, 4),
    //     make_token(TokenType::EOF, "", 1, 5)
    // ]
//     vec![
//     make_token(TokenType::IF, "if", 1, 1),
//     make_token(TokenType::LPAREN, "(", 1, 4),
//     make_token(TokenType::NUMBER, "2", 1, 5),
//     make_token(TokenType::PLUS, "+", 1, 7),
//     make_token(TokenType::NUMBER, "2", 1, 9),
//     make_token(TokenType::GT, ">", 1, 11),
//     make_token(TokenType::NUMBER, "4", 1, 13),
//     make_token(TokenType::RPAREN, ")", 1, 14),
//     make_token(TokenType::LBRACE, "{", 1, 16),
//     make_token(TokenType::LET, "let", 2, 5),
//     make_token(TokenType::IDENT, "a", 2, 9),
//     make_token(TokenType::ASSIGN, "=", 2, 11),
//     make_token(TokenType::STRING, "\"true\"", 2, 13),
//     make_token(TokenType::IN, "in", 2, 20),
//     make_token(TokenType::IDENT, "a", 2, 23),
//     make_token(TokenType::SEMICOLON, ";", 2, 24),
//     make_token(TokenType::RBRACE, "}", 3, 1),

//     make_token(TokenType::ELIF, "elif", 4, 1),
//     make_token(TokenType::LPAREN, "(", 4, 6),
//     make_token(TokenType::NUMBER, "2", 4, 7),
//     make_token(TokenType::PLUS, "+", 4, 9),
//     make_token(TokenType::NUMBER, "2", 4, 11),
//     make_token(TokenType::LT, "<", 4, 13),
//     make_token(TokenType::NUMBER, "4", 4, 15),
//     make_token(TokenType::RPAREN, ")", 4, 16),
//     make_token(TokenType::LBRACE, "{", 4, 18),
//     make_token(TokenType::LET, "let", 5, 5),
//     make_token(TokenType::IDENT, "a", 5, 9),
//     make_token(TokenType::ASSIGN, "=", 5, 11),
//     make_token(TokenType::STRING, "\"true\"", 5, 13),
//     make_token(TokenType::IN, "in", 5, 20),
//     make_token(TokenType::IDENT, "a", 5, 23),
//     make_token(TokenType::SEMICOLON, ";", 5, 24),
//     make_token(TokenType::RBRACE, "}", 6, 1),

//     make_token(TokenType::ELIF, "elif", 7, 1),
//     make_token(TokenType::LPAREN, "(", 7, 6),
//     make_token(TokenType::NUMBER, "2", 7, 7),
//     make_token(TokenType::PLUS, "+", 7, 9),
//     make_token(TokenType::NUMBER, "2", 7, 11),
//     make_token(TokenType::LE, "<=", 7, 13),
//     make_token(TokenType::NUMBER, "4", 7, 16),
//     make_token(TokenType::RPAREN, ")", 7, 17),
//     make_token(TokenType::LBRACE, "{", 7, 19),
//     make_token(TokenType::LET, "let", 8, 5),
//     make_token(TokenType::IDENT, "a", 8, 9),
//     make_token(TokenType::ASSIGN, "=", 8, 11),
//     make_token(TokenType::STRING, "\"true\"", 8, 13),
//     make_token(TokenType::IN, "in", 8, 20),
//     make_token(TokenType::IDENT, "a", 8, 23),
//     make_token(TokenType::SEMICOLON, ";", 8, 24),
//     make_token(TokenType::RBRACE, "}", 9, 1),

//     make_token(TokenType::ELSE, "else", 10, 1),
//     make_token(TokenType::LBRACE, "{", 10, 6),
//     make_token(TokenType::STRING, "\"2\"", 11, 5),
//     make_token(TokenType::SEMICOLON, ";", 11, 9),
//     make_token(TokenType::RBRACE, "}", 12, 1),
//     make_token(TokenType::SEMICOLON, ";", 12, 2),
//     make_token(TokenType::EOF, "", 13, 1),
// ]

vec![
    // type Point (x, y) { ... }
    make_token(TokenType::TYPE, "type", 1, 1),
    make_token(TokenType::IDENT, "Point", 1, 6),
    make_token(TokenType::LPAREN, "(", 1, 12),
    make_token(TokenType::IDENT, "x", 1, 13),
    make_token(TokenType::COMMA, ",", 1, 22),
    make_token(TokenType::IDENT, "y", 1, 24),
    make_token(TokenType::RPAREN, ")", 1, 33),
    make_token(TokenType::LBRACE, "{", 1, 35),

    // x = x;
    make_token(TokenType::IDENT, "x", 2, 13),
    make_token(TokenType::ASSIGN, "=", 2, 15),
    make_token(TokenType::IDENT, "x", 2, 17),
    make_token(TokenType::SEMICOLON, ";", 2, 18),

    // y = y;
    make_token(TokenType::IDENT, "y", 3, 13),
    make_token(TokenType::ASSIGN, "=", 3, 15),
    make_token(TokenType::IDENT, "y", 3, 17),
    make_token(TokenType::SEMICOLON, ";", 3, 18),

    // getX()  => self.x;
    make_token(TokenType::IDENT, "getX", 5, 13),
    make_token(TokenType::LPAREN, "(", 5, 18),
    make_token(TokenType::RPAREN, ")", 5, 19),
    make_token(TokenType::ARROW, "=>", 5, 30),
    make_token(TokenType::SELF, "self", 5, 33),
    make_token(TokenType::DOT, ".", 5, 37),
    make_token(TokenType::IDENT, "x", 5, 38),
    make_token(TokenType::SEMICOLON, ";", 5, 39),

    // getY()  => self.y;
    make_token(TokenType::IDENT, "getY", 6, 13),
    make_token(TokenType::LPAREN, "(", 6, 18),
    make_token(TokenType::RPAREN, ")", 6, 19),
    make_token(TokenType::ARROW, "=>", 6, 30),
    make_token(TokenType::SELF, "self", 6, 33),
    make_token(TokenType::DOT, ".", 6, 37),
    make_token(TokenType::IDENT, "y", 6, 38),
    make_token(TokenType::SEMICOLON, ";", 6, 39),

    // setX(x)  => self.x := x ;
    make_token(TokenType::IDENT, "setX", 8, 13),
    make_token(TokenType::LPAREN, "(", 8, 18),
    make_token(TokenType::IDENT, "x", 8, 19),
    make_token(TokenType::RPAREN, ")", 8, 28),
    make_token(TokenType::ARROW, "=>", 8, 39),
    make_token(TokenType::SELF, "self", 8, 42),
    make_token(TokenType::DOT, ".", 8, 46),
    make_token(TokenType::IDENT, "x", 8, 47),
    make_token(TokenType::ASSIGN_DESTRUCT, ":=", 8, 49),
    make_token(TokenType::IDENT, "x", 8, 52),
    make_token(TokenType::SEMICOLON, ";", 8, 53),

    // setY(y)  => self.y := y ;
    make_token(TokenType::IDENT, "setY", 9, 13),
    make_token(TokenType::LPAREN, "(", 9, 18),
    make_token(TokenType::IDENT, "y", 9, 19),
    make_token(TokenType::RPAREN, ")", 9, 28),
    make_token(TokenType::ARROW, "=>", 9, 39),
    make_token(TokenType::SELF, "self", 9, 42),
    make_token(TokenType::DOT, ".", 9, 46),
    make_token(TokenType::IDENT, "y", 9, 47),
    make_token(TokenType::ASSIGN_DESTRUCT, ":=", 9, 49),
    make_token(TokenType::IDENT, "y", 9, 52),
    make_token(TokenType::SEMICOLON, ";", 9, 53),

    make_token(TokenType::RBRACE, "}", 10, 9),
    make_token(TokenType::SEMICOLON, ";", 10, 10),

    // let x = new Point(3, 4) in (x.getX() + x.getY());
    make_token(TokenType::LET, "let", 12, 1),
    make_token(TokenType::IDENT, "x", 12, 5),
    make_token(TokenType::ASSIGN, "=", 12, 7),
    make_token(TokenType::NEW, "new", 12, 9),
    make_token(TokenType::IDENT, "Point", 12, 13),
    make_token(TokenType::LPAREN, "(", 12, 18),
    make_token(TokenType::NUMBER, "3", 12, 19),
    make_token(TokenType::COMMA, ",", 12, 20),
    make_token(TokenType::NUMBER, "4", 12, 22),
    make_token(TokenType::RPAREN, ")", 12, 23),
    make_token(TokenType::IN, "in", 12, 25),
    make_token(TokenType::LPAREN, "(", 12, 28),
    make_token(TokenType::IDENT, "x", 12, 29),
    make_token(TokenType::DOT, ".", 12, 30),
    make_token(TokenType::IDENT, "getX", 12, 31),
    make_token(TokenType::LPAREN, "(", 12, 36),
    make_token(TokenType::RPAREN, ")", 12, 37),
    make_token(TokenType::PLUS, "+", 12, 39),
    make_token(TokenType::IDENT, "x", 12, 41),
    make_token(TokenType::DOT, ".", 12, 42),
    make_token(TokenType::IDENT, "getY", 12, 43),
    make_token(TokenType::LPAREN, "(", 12, 48),
    make_token(TokenType::RPAREN, ")", 12, 49),
    make_token(TokenType::RPAREN, ")", 12, 50),
    make_token(TokenType::SEMICOLON, ";", 12, 51),

    // for ( i in range(1,10) ) { ... }
    make_token(TokenType::FOR, "for", 15, 1),
    make_token(TokenType::LPAREN, "(", 15, 5),
    make_token(TokenType::IDENT, "i", 15, 7),
    make_token(TokenType::IN, "in", 15, 9),
    make_token(TokenType::IDENT, "range", 15, 12),
    make_token(TokenType::LPAREN, "(", 15, 17),
    make_token(TokenType::NUMBER, "1", 15, 18),
    make_token(TokenType::COMMA, ",", 15, 19),
    make_token(TokenType::NUMBER, "10", 15, 21),
    make_token(TokenType::RPAREN, ")", 15, 23),
    make_token(TokenType::RPAREN, ")", 15, 24),
    make_token(TokenType::LBRACE, "{", 15, 26),

    // if ( i > 5 ) { print("i"); } else { "hola"; }
    make_token(TokenType::IF, "if", 16, 5),
    make_token(TokenType::LPAREN, "(", 16, 8),
    make_token(TokenType::IDENT, "i", 16, 9),
    make_token(TokenType::GT, ">", 16, 11),
    make_token(TokenType::NUMBER, "5", 16, 13),
    make_token(TokenType::RPAREN, ")", 16, 14),
    make_token(TokenType::LBRACE, "{", 16, 16),
    make_token(TokenType::IDENT, "print", 17, 9),
    make_token(TokenType::LPAREN, "(", 17, 14),
    make_token(TokenType::STRING, "\"i\"", 17, 15),
    make_token(TokenType::RPAREN, ")", 17, 18),
    make_token(TokenType::SEMICOLON, ";", 17, 19),
    make_token(TokenType::RBRACE, "}", 18, 5),
    make_token(TokenType::ELSE, "else", 18, 7),
    make_token(TokenType::LBRACE, "{", 18, 12),
    make_token(TokenType::STRING, "\"hola\"", 19, 9),
    make_token(TokenType::SEMICOLON, ";", 19, 15),
    make_token(TokenType::RBRACE, "}", 20, 5),
    make_token(TokenType::SEMICOLON, ";", 20, 6),
    make_token(TokenType::RBRACE, "}", 21, 1),
    make_token(TokenType::SEMICOLON, ";", 21, 2),

    // let x = 5 in ( x + x );
    make_token(TokenType::LET, "let", 23, 1),
    make_token(TokenType::IDENT, "x", 23, 5),
    make_token(TokenType::ASSIGN, "=", 23, 7),
    make_token(TokenType::NUMBER, "5", 23, 9),
    make_token(TokenType::IN, "in", 23, 11),
    make_token(TokenType::LPAREN, "(", 23, 14),
    make_token(TokenType::IDENT, "x", 23, 15),
    make_token(TokenType::PLUS, "+", 23, 17),
    make_token(TokenType::IDENT, "x", 23, 19),
    make_token(TokenType::RPAREN, ")", 23, 20),
    make_token(TokenType::SEMICOLON, ";", 23, 21),

    // let y = 4 , z = 3 in ( y + z );
    make_token(TokenType::LET, "let", 24, 1),
    make_token(TokenType::IDENT, "y", 24, 5),
    make_token(TokenType::ASSIGN, "=", 24, 7),
    make_token(TokenType::NUMBER, "4", 24, 9),
    make_token(TokenType::COMMA, ",", 24, 10),
    make_token(TokenType::IDENT, "z", 24, 12),
    make_token(TokenType::ASSIGN, "=", 24, 14),
    make_token(TokenType::NUMBER, "3", 24, 16),
    make_token(TokenType::IN, "in", 24, 18),
    make_token(TokenType::LPAREN, "(", 24, 21),
    make_token(TokenType::IDENT, "y", 24, 22),
    make_token(TokenType::PLUS, "+", 24, 24),
    make_token(TokenType::IDENT, "z", 24, 26),
    make_token(TokenType::RPAREN, ")", 24, 27),
    make_token(TokenType::SEMICOLON, ";", 24, 28),

    // while ( !(3 < 4) ) { "hola"; };
    make_token(TokenType::WHILE, "while", 25, 1),
    make_token(TokenType::LPAREN, "(", 25, 7),
    make_token(TokenType::MINUS, "!", 25, 8),
    make_token(TokenType::LPAREN, "(", 25, 9),
    make_token(TokenType::NUMBER, "3", 25, 10),
    make_token(TokenType::LT, "<", 25, 12),
    make_token(TokenType::NUMBER, "4", 25, 14),
    make_token(TokenType::RPAREN, ")", 25, 15),
    make_token(TokenType::RPAREN, ")", 25, 16),
    make_token(TokenType::LBRACE, "{", 25, 18),
    make_token(TokenType::STRING, "\"hola\"", 26, 5),
    make_token(TokenType::SEMICOLON, ";", 26, 11),
    make_token(TokenType::RBRACE, "}", 27, 1),
    make_token(TokenType::SEMICOLON, ";", 27, 2),

    make_token(TokenType::EOF, "", 28, 1),
    
]

}
